
* 202407
* Book:
** Book: Traction: How Any Startup Can Achieve Explosive Customer Growth
** Link: https://www.amazon.com/Traction-Startup-Achieve-Explosive-Customer-ebook/dp/B00TY3ZOMS?ref_=ast_author_mpb
** Notes:
- Traction is the best way to improve your chances of startup success. Traction is a signthat something is working. If you charge for your product, it means customers are
buying. If your product is free, it’s a growing user base. 
Traction is powerful. Technical, market, and team risks are easier to address with
traction. Fund-raising, hiring, press, partnerships, and acquisitions all become much
easier. 
In other words, traction trumps everything.

-  Founders have an idea for a company they’re excited about. Initial excitement turns
into a struggle to build a product, but they do get something out the door. 

-  Traction is a sign that your company is
taking off. It’s obvious in your core metrics: If you have a mobile app, your download
rate is growing rapidly. If you’re running a subscription service, your monthly revenue is
skyrocketing. If you’re an organic bakery, your number of transactions is increasing
every week. You get the point. 

- Traction is basically quantitative evidence of customer demand. So if you’re in enterprise
software, [initial traction] may be two or three early customers who are paying a bit; if
you’re in consumer software the bar might be as high as hundreds of thousands of users.   --- Naval

- A startup is a company designed to grow fast. Being newly founded does not in itself make
a company a startup. Nor is it necessary for a startup to work on technology, or take
venture funding, or have some sort of “exit.” The only essential thing is growth. Everything
else we associate with startups follows from growth. 

Traction is growth. The pursuit of traction is what defines a startup.

- The number one reason that we pass on entrepreneurs we’d otherwise like to back is
they’re focusing on product to the exclusion of everything else. Many entrepreneurs who
build great products simply don’t have a good distribution strategy. Even worse is when
they insist that they don’t need one, or call [their] no distribution strategy a “viral
marketing strategy.”

- Having a product or service that your early customers love, but having no clear way to
get more traction is a major problem. To solve this problem, spend your time
constructing your product or service and testing traction channels in parallel.

- Traction and product development are of equal importance and should each get about
half of your attention. This is what we call the 50 percent rule: spend 50 percent of
your time on product and 50 percent on traction.

- First, you could build something people want, but for which you just can’t figure out a
viable business model. The money isn’t adding up. For example, people won’t pay, and
selling advertising won’t cover the bills. There is just no real market. 

  Second, you could build something people want, but there are just not enough
customers to reach profitability. It’s just too small a market, and there aren’t obvious
ways to expand. This occurs often when startups aren’t ambitious enough and pick too
narrow a niche.

- Third, you could build something people want, but reaching them is cost prohibitive.
You find yourself in a hard-to-reach market. An example is a relatively inexpensive
product that requires a direct sales force to sell it. That combo just doesn’t work. 

- Finally, you could build something people want, but a lot of other companies build it
too. In this situation you are in a hypercompetitive market where it is simply too hard to
get customers.

- If you follow the 50 percent rule from the beginning, then you will have the best
chance of avoiding these traps. If you don’t, then you risk realizing you’re in one of
these traps too late to do anything useful. Unfortunately this happens to a lot of
companies postlaunch. The sad thing is that often these products and services are
useful, =but the companies die because they don’t have a good distribution strategy.=

- First, it helps you build the right product because you can incorporate knowledge from
your traction efforts. If you’re following a good product development process, you’re
already getting good feedback from early customers. However, these customers are
generally too close to you. They often tell you what you want to hear.

- Through traction development you get a steady stream of cold customers. It is through
these people that you can really find out whether the market is taking to your product
or not, and if not, what features are missing or which parts of the experience are
broken.

- You can think of your initial investment in traction as pouring water into a leaky bucket.
At first your bucket will be very leaky because your product is not yet a full solution to
customer needs and problems. In other words, your product is not as sticky as it could
be, and many customers will not want to engage with it yet. As a consequence, much of
the money you are spending on traction will leak out of your bucket.

- This is exactly what happened with Dropbox. While developing their product, they
tested search engine marketing and found it wouldn’t work for their business. They
were acquiring customers for $230 when their product cost only $99. That’s when they
focused on the viral marketing traction channel, and built a referral program right into
their product. This program has since been their biggest growth driver.

- From the perspective of getting traction, you can think about working on a product or
service in three phases: 
    Phase I—making something people want 

    Phase II—marketing something people want 

    Phase III—scaling your business

- As Paul Graham said in his essay “Do Things That Don’t Scale”: 
A lot of would-be founders believe that startups either take off or don’t. You build
something, make it available, and if you’ve made a better mousetrap, people beat a path
to your door as promised. Or they don’t, in which case the market must not exist. 
Actually startups take off because the founders make them take off. . . .

The most common unscalable thing founders have to do at the start is to recruit users manually. Nearly all
startups have to. You can’t wait for users to come to you. You have to go out and get them.

- =We strongly believe that many startups give up way too early.= A lot of startup success
hinges on choosing a great market at the right time. Consider DuckDuckGo, the search
engine startup that Gabriel founded. Other search startups gave up after two years:
Gabriel has been at it for more than seven. 

- =Put half your efforts into getting traction.= Pursue traction and product
development in parallel, and spend equal time on both. Think of your product as
a leaky bucket. Your early traction efforts are pointing you toward the holes
worth plugging.

- =Set your growth goals.= Focus on strategies and tactics that can plausibly move
the needle for your company. Get some hard numbers.

- =Learn what growth numbers potential investors respect.= How much traction is
needed for investors is a moving target, but a sustainable customer growth rate
is hard for investors to ignore. Potential investors who understand your business
are likely to appreciate your traction and thus invest earlier. Traction trumps
everything.

- =Find your bright spots.= If you’re not seeing the traction you want, look for bright
spots in your customer base, pockets of customers who are truly engaged with
your product. See if you can figure out why it works for them and if you can
expand from that base. If there are no bright spots, it may be a good time to
pivot.

- __[You] probably won’t have a bunch of equally good distribution strategies. Engineers
frequently fall victim to this because they do not understand distribution. Since they don’t
know what works, and haven’t thought about it, they try some sales, BD, advertising, and
viral marketing—everything but the kitchen sink. 
That is a really bad idea. It is very likely that one channel is optimal. Most businesses
actually get zero distribution channels to work. =Poor distribution—not product—is the
number one cause of failure.= If you can get even a single distribution channel to work, you
have great business. If you try for several but don’t nail one, you’re finished. So it’s worth
thinking really hard about finding the single best distribution channel.__

- Bullseye: 
   1. what's possible: If you were to advertise offline, where would be the best place to do it? If you were to give a speech,
who would be the ideal audience? Imagine what success would look like in each channel, and write it down in your outer ring.
   2. what’s probable: 
      * How much will it cost to acquire customers through this channel? 
      * How many customers are available through this channel? 
      * Are the customers that you are getting through this channel the kind of customers that you want right now? 
   3. what’s working:  In that case, you should start directing all your traction efforts and resources toward this most promising channel. You hit the Bullseye! You’ve found your
core channel. The goal of this focusing step is quite simple: to wring every bit of traction out of your core channel.

- The biggest mistake startups make when trying to get traction is failing to pursue
traction in parallel with product development. Many entrepreneurs think that if you
build a killer product, your customers will beat a path to your door. =This line of thinking
is a fallacy: that the best use of your time is always improving your product.= =In other
words, “if you build it, they will come” is wrong.=

** Book: The Psychology of Man's Possible Evolution
** Link: https://www.amazon.com/Psychology-Mans-Possible-Evolution/dp/0394719433
** Notes:

- Our fundamental idea shall be that man as we know him is not a completed being; that nature develops him only up to a certain point and then leaves him, to develop further, by his own efforts and devices, or to live and die such as he was born, or to degenerate and lose capacity for development.
- Evolution of man in this case will mean the development of certain inner qualities and features which usually remain undeveloped, and cannot develop by themselves.


** Book: What the CEO Wants You to Know : How Your Company Really Works
** Link: https://www.amazon.com/What-CEO-Wants-You-Know/dp/0609608398
** Notes:

- The best CEOs have a knack for bringing the most complex business down to the fundamen- tals the same fundamentals of the family shoe shop.
  They have business acumen the ability to focus on the basics and make money for the company.
- The one thing I’ve noticed is that the best CEOs—the ones whose companies make money year after year—are like the best teacher you ever had. They are able to take the complexity and mystery out of business by focusing on the core fundamentals.
- And as the company has profitable growth—that is, both sales (the “top line”) and profits (the “bottom line”) increase year after year—there are greater opportunities for people to expand their careers and to make more money.
- They have what I call business acumen the ability to understand the building blocks of how a one-person operation or a very big business makes money.
- Once you understood that the atom was made up of protons, electrons, and neutrons, you then had the fundamentals to solve any problem in chemistry. I want to show you that it's the same with business: When you know the fundamentals, you can "get" the basics for how any business works.
- The most successful business leaders never lose sight of the basics. Their intense focus on the fundamentals of business is, in fact, the secret to their success. Like the street vendor, they have a keen sense of how a business makes money. This ability to apply the universal laws of business is what I call business acumen.
- Such career tracks tend to narrow your perspective and influence the decisions and trade-offs you make every day. What's best for your department or function is not necessarily best for the company as a whole. You may be a top-notch professional good marketing but are you at or engineering or financial analysis a businessperson? Regardless of your job, really depart- ment, or chimney, you need to develop your business acumen.
- When you learn to speak the universal language of business, you can have meaningful discussions with anyone in the company, at any level. You'll tear down the walls that separate you, a functional chimney per- son, from those well-dressed senior executives and MBAs who speak a language you may not understand. You'll feel more connected to your company and your work. And the range of opportunities open to you will expand.
- If, on the other hand, he gives people a good deal every time, he builds their trust and loyalty to his brand. He has to be consumer focused.
- Money making in business has three basic parts: cash generation, return on assets a combination of margin and velocity, and growth.
- Cut through to the nucleus of the business. If your business shows deterioration in one or more of the basic components of money making, use common sense to fix it. If you do, you are on your way to thinking and acting like a true businessperson and a successful CEO!
- Cash generation is the difference between all the cash that flows into the business and all the cash that flows out of the business in a given time period. Cash flows into the corporation from sources like the sales of its product or services that are paid for in cash and payments by customers for previous sales made on credit. Cash flows out of the business for items like salaries, taxes, and payments to suppliers.
- But most companies extend credit, so cash and income are different. They make a sale now but collect the money later. They buy something now and pay for it later. They have accounts receivable (money customers owe them) and accounts payable (money they owe their suppliers). The timing of these payments affects cash generation.
- Cash gives you the ability to stay in business. It is a company's oxygen supply. Lack of cash, decreasing cash, or consumption of cash spells trouble, even if the other elements of money making gin and asset velocity  such as profit look good.
- Regardless of the size or kind of business, you're using your own or someone else's money to grow. You borrow from a bank or use your savings. That money represents your investment, or your investment capital. If you inherit the business, the "investment" is given to you.
- The things you've invested in are assets. The assets of an automobile manufacturer include the factories and assembly plants, office buildings, computer systems, and inventories of sheet metal, paint, and components.
- These are tangible assets you can see and touch. The big items, like buildings and machinery, that are not expected to be sold are sometimes called fixed assets.
- Find out the tangible assets in your company. A person with great business acumen will wonder how much money you are able to make with those assets. What kind of money is being returned to you through their use? In short, what is your return on assets, your ROA? Are you making enough of a return on those assets?
- The word velocity describes this idea of speed, turnover, or movement. Think of raw materials moving through a factory and becoming finished products, and think of those finished products moving off the shelf to the customer. That's velocity.
- Some people use the term inventory turns to describe inventory velocity. How many times does the inventory turn over in a year? Wal-Mart has 360 inven- tory turns in toilet tissue. That means the entire inven- tory of toilet tissue is sold almost every day. Each day, Wal-Mart gets back the money it spent on its inventory of toilet tissue, plus some profit. That's a terrific use of shelf space.
- But forget the math. Get the idea of velocity. Things must move through a business to the customer the faster, the better.
- The faster the velocity, the higher the return. In fact, return on assets is nothing more than profit margin multiplied by asset velocity. This is a universal law of business that can be written simply:
        Return = Margin x Velocity
  or
        R = M x V
- Gross margin, from which net profit margin is derived, is also critical to understanding the fundamental anatomy of the business. Gross margin is calculated by taking the total sales for the company or a product line and subtracting the costs directly associated with making or buying the product or service.
- Every business must earn a return that is greater than the cost of using other people’s money (banks’, shareholders’, or owners’). To keep this truth front and center, many companies today are using a measure called shareholder value added. SVA is a kind of shorthand for judging how well the business is performing overall. Is it or is it not meeting the basic requirements of investors?
- So don't use size as a measure of success. Pushing for more sales dollars isn't necessarily good business. You have to know how and why you're growing. And you have to consider whether you are growing in a way that can continue.
- Look at what is happening to your cash. Maybe sales are increasing, but the cash situation is getting worse. Step back. Are you growing in a way that is gen- erating or consuming cash? Is your profit margin improving or getting worse? money making is improving and the cash is growing too, you have some interesting choices. You If the can use the funds to develop a new product, buy another company, or expand into a new country. Maybe you want to add some new features to make your prod- uct more appealing. Maybe you can cut the price and expand demand profitably.
- The elements of money making cash generation, margin, velocity, return on assets, and growth can all be measured. But people with business acumen don't just memorize these words like terms in a textbook. They understand their real meaning, instinctively sense their relationships to one another, and use them to cre- ate a mental picture. True businesspeople combine the elements of money making to get an intuitive grasp of the total business.
- Exceptional business leaders do what no computer can do. They scan the external environment, and out of all the things that are going on in the world, they are able to identify the significant patterns and trends.
- Business acumen helps a CEO choose the three or four business priorities (no more than five) that will retain customers and achieve all the important money making goals at the same time
  all in the context of the real world.
- Maybe you're an engineer designing a new product. How does it fit into the company's total money-making picture? Will the design please customers and earn a good margin? Does it have the features lots of customers want? Is it preferred by customers over that of a com- ^petitor? Is it going to require new equipment and thus consume cash and reduce velocity? Or is it simply an extension of some existing products and therefore uses equipment or tooling the company already has?
- The main task for the CEO of a publicly traded company goes beyond money making. Shareholders (and employ- ees who receive stock options as part of their compen- sation) expect a CEO to create wealth for them. The best CEOs understand that money making and wealth cre- ation are linked through what is known as the price also called the P-E multiple, or P-E earnings multiple ratio. The P is the price of an individual share of stock. The E is earnings per share —how much profit the company made for each share of stock.
- Find out what your company's P-E multiple is and how the multiple compares to that of its peers and the S&P 500. Then take a minute to reflect: Have you and your company been focused on consistent, predictable, profitable growth; sustainable sources of cash genera- tion; improved margin and/or velocity; and thus return on assets, quarter by quarter? Are all of these combined better than your competitors', and are they improving against that of the S&P 500?
- The investment com- munity tends to reward such CEOs and companies with a higher P-E multiple, which creates tremendous wealth for shareholders. It creates job security and growth opportunities for employees, and wealth for those who receive stock options.
- As any CEO knows well, in business, there are quarterly milestones but there are no finishing lines. Leaders have to deliver results day in, day out, relent- lessly over a long period of time. Delivering results is what gives an organization energy, builds confidence, and generates the resources to go forward.
- Whether you're a CEO, the head of a department, or someone just starting his career, you must be a leader of the business and a leader of people. =A leader of the business knows what to do. A leader of people knows how to get it done:= Harness the efforts of other people, expand their personal capacity, and synchronize their efforts to get results. If you do all that, you get results. That's what I call an edge in execution.
- People who do well in a job also need attention. A true leader of people expands their capacity by helping them channel their skills, develop their abilities, and release their positive energy. Expanding capacity may mean giving the person a "stretch job" that will force him to develop a new skill or gain a new perspective.
- If the person gets the feedback right away and makes the correction, the company will perform better. It's an edge in execution.
- The moment you create that structure, the social interaction in the organization changes. Often, the information that flows from one part of the organization to another gets clogged or distorted. The bigger the company, the harder it is for people to share information, make joint decisions, and adjust their priorities. Decision making slows. The edge in execution gets blunted.
- The lack of synchronization explains why so many small shopkeepers and vendors never expand. They do not know how to create mechanisms that bring people together in a meaningful way, expand their individual capacity, and build the capacity of the total business.
- What are the regional managers observing if they're doing the job right? Not just prices. They're seeing the merchandise, how it is presented, what consumers are buying, what the stores look like, what the ambience is, what new practices competitors are using, and how employees are behaving. Go back to the fundamentals. Remember con- sumers. Who are they and what are they buying? Is your business offering sustainable for the future? You assess through competitive analysis, which for Wal-Mart this was going on constantly.
- Designing Social Operating Mechanisms is a leader- ship task, not a human resources department task. Use your creativity and take it on as a personal challenge.
- You don't have to be a CEO to practice being a leader of the business and a leader of people. Say you're a product line manager. The thought process is the same. Assess the fundamentals of the product line and consider why they are going one way or the other and how they might be improved. When you know what must be done, think about the people around you. Do they have the skills and talents required? How can you coach them? What kind of Social Operating Mechanisms might speed the flow of information and decisions?
- Some of you have the intellectual capacity to cut through complexity but are indecisive or afraid of being wrong. Can you wait until all the facts are in and the picture is clearer? Here's the rub: =You make a bet even when you don't make a bet!= That is, by not choosing to do anything different, you are choosing the status quo.


